### ISSUE TITLE
WIki の画像が表示されない

### ISSUE THREAD

**Issue by automatic9045** [stop-pattern/AtsExCsTemplate#10]
[クイックスタート](https://github.com/stop-pattern/AtsExCsTemplate/wiki/%E3%82%AF%E3%82%A4%E3%83%83%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88) 等の Wiki のページにて、当方の環境では画像が正しく表示されないのですが、画像を削除してしまったりしていないでしょうか？

昨日のとある時点までは表示できていた記憶です。ご確認いただけると嬉しいです。

![image](https://github.com/stop-pattern/AtsExCsTemplate/assets/67314487/baeea471-236f-4d8d-a588-175469c623d4)

**Comment by TetsuOtter** [comment]
@stop-pattern 
GitHubのWikiに画像を貼り付けてもなぜかPrivateになって見れなくなってしまう不具合があるようで、私も悩まされました。
一旦Wikiをgit repositoryとしてcloneして、そこに手動で画像を配置してリンクも直してcommit & pushで解消します

**Comment by stop-pattern** [comment]
昨日のmainマージ前の時点では画像が見れたのはこちらでも確認しています
画像は消してないはずなのでなんで消えたのか分かりません…
後で確認して直します

@TetsuOtter 解決策ありがとうございます🙇

**Comment by stop-pattern** [comment]
画像自体はawsに残ってたのでこれをwikiのサブディレクトリに保管してそれを参照するように変更しました  
こちらの環境では問題は解決したように思われます  
一応他の環境でも問題ないことが確認出来てから閉じたいので、恐れ入りますが確認をお願いします:bow:

**Comment by TetsuOtter** [comment]
> 画像自体はawsに残ってたのでこれをwikiのサブディレクトリに保管してそれを参照するように変更しました こちらの環境では問題は解決したように思われます 一応他の環境でも問題ないことが確認出来てから閉じたいので、恐れ入りますが確認をお願いします 🙇

私の環境では今のところ問題無く見れています。
消えるとしたら少し経ってのはずなので、明後日辺りにまた確認してみます

**Comment by automatic9045** [comment]
ご対応ありがとうございます。こちらの環境でも現時点では正しく表示されています。
明日、明後日あたりにもう一度確認してみますね。

**Comment by stop-pattern** [comment]
数日たったので確認しましたが問題なさそうなので閉じます
